version: '3.7'
services:
  prometheus:
    image: prom/prometheus:main
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:main
    ports:
      - "3000:3000"
