global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ms-springboot-actuator'
    metrics_path: '/ms-rest-api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.172:8081']
    basic_auth:
      username: "monitor"
      password: "monitor123"